import { SignInButton, useUser, SignOutButton } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";
import { CreatePost } from "~/components/CreatePost";
import Image from "next/image";
import { PostView } from "~/components/PostCard";
import Loader from "~/components/Loader";

const Home: NextPage = () => {
  const { isSignedIn, user } = useUser();

  const { data, isLoading } = api.posts.getAll.useQuery();

  if (isLoading) {
    return <Loader size="large" />;
  }

  if (!data) {
    return <div>Failed to load</div>;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center bg-primary text-primary-foreground">
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
          <div className="flex border-b border-slate-400 p-4">
            {!isSignedIn && (
              <div className="flex justify-center ">
                <SignInButton />
              </div>
            )}
            {isSignedIn && (
              <div className="flex w-full justify-between">
                <Image
                  alt="profile image"
                  src={user.profileImageUrl}
                  width={32}
                  height={32}
                  className="h-12 w-12 rounded-full"
                />
                <CreatePost className="my-auto" />
                <SignOutButton />
              </div>
            )}
          </div>

          <div>
            {data?.map((fullPost) => {
              return (
                <div key={fullPost.post.id} className="mx-4 my-4 flex gap-2">
                  <PostView {...fullPost} />
                </div>
              );
            })}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
