import { SignIn, SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { api } from "~/utils/api";

const Home: NextPage = () => {
  const user = useUser();

  const { data } = api.posts.getAll.useQuery();
  console.log("🚀 ~ file: index.tsx:10 ~ data:", data);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="color: white">
          <h1 className="text-4xl font-bold text-white">
            {user.isSignedIn ? <SignOutButton /> : <SignInButton />}
          </h1>
        </div>
        <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />

        <div className="content">
          {data?.map((post) => (
            <div className="text-white" key={post.id}>
              {post.content}
            </div>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
